version: '3.8'

services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
        GID: ${GID}
    image: my-angular-20-app-dev
    container_name: my-angular-20-container
    ports:
      - "4200:4200"
    volumes:
      - .:/app:z
      - angular_node_modules:/app/node_modules
    user: "${UID}:${GID}"
    command: sleep infinity
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  angular_node_modules:
