FROM node:20-alpine

ARG UID=1000
ARG GID=1000

RUN apk update && apk add --no-cache git bash openssh-client && rm -rf /var/cache/apk/*

RUN \
  if ! getent group ${GID} > /dev/null; then \
    addgroup -g ${GID} appgroup; \
  fi && \
  GROUP_NAME=$(getent group ${GID} | cut -d: -f1) && \
  if ! getent passwd ${UID} > /dev/null; then \
    adduser -D -u ${UID} -G ${GROUP_NAME} -s /bin/sh appuser; \
  fi

USER ${UID}

WORKDIR /app

RUN mkdir -p /app/node_modules

EXPOSE 4200

CMD ["tail", "-f", "/dev/null"]
